fix script

diff --git a/.github/workflows/build-libheif.yaml b/.github/workflows/build-libheif.yaml
--- a/.github/workflows/build-libheif.yaml
+++ b/.github/workflows/build-libheif.yaml
@@ -54,6 +54,18 @@ jobs:
             exit 1
           fi
 
+      # 3.5 修改 build-emscripten.sh 中 AOM URL
+      - name: Patch build-emscripten.sh AOM URL
+        run: |
+          FILE="$SRC_DIR/build-emscripten.sh"
+          if [ ! -f "$FILE" ]; then
+            echo "Error: $FILE not found!"
+            exit 1
+          fi
+
+          sed -i 's|https://aomedia.googlesource.com/aom/+archive|https://github.com/aetstapa/heifjs/releases/download/v0.0.1|g' "$FILE"
+          echo "Patched build-emscripten.sh successfully."
+
       # 4. 安装 Emscripten 并持久化环境变量
       - name: Install Emscripten
         run: |
